name: Xcode - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    name: Build and test Swift project
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Xcode command line tools
        run: sudo xcode-select --install || true  # Install command line tools if not already installed
      
      - name: Build and Test
        run: |
          xcodebuild clean build test \
            -project YourProject.xcodeproj \  # Adjust the project name
            -scheme YourScheme \  # Adjust the scheme name
            -destination 'platform=macOS' \
            -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}
